# Optional Lab: Python, NumPy và Vectorization
Giới thiệu ngắn gọn về một số tính toán khoa học được sử dụng trong khóa học này. Đặc biệt là máy tính khoa học NumPy package và việc sử dụng nó với python.

# Outline
- [&nbsp;&nbsp;1.1 Goals](#toc_40015_1.1)
- [&nbsp;&nbsp;1.2 Useful References](#toc_40015_1.2)
- [2 Python and NumPy <a name='Python and NumPy'></a>](#toc_40015_2)
- [3 Vectors](#toc_40015_3)
- [&nbsp;&nbsp;3.1 Abstract](#toc_40015_3.1)
- [&nbsp;&nbsp;3.2 NumPy Arrays](#toc_40015_3.2)
- [&nbsp;&nbsp;3.3 Vector Creation](#toc_40015_3.3)
- [&nbsp;&nbsp;3.4 Operations on Vectors](#toc_40015_3.4)
- [4 Matrices](#toc_40015_4)
- [&nbsp;&nbsp;4.1 Abstract](#toc_40015_4.1)
- [&nbsp;&nbsp;4.2 NumPy Arrays](#toc_40015_4.2)
- [&nbsp;&nbsp;4.3 Matrix Creation](#toc_40015_4.3)
- [&nbsp;&nbsp;4.4 Operations on Matrices](#toc_40015_4.4)


In [1]:
import numpy as np    # it is an unofficial standard to use np for numpy
import time

<a name="toc_40015_1.1"></a>
## 1.1 Bàn thắng
Trong lab này, bạn sẽ:
- Ôn lại features của NumPy và Python được sử dụng trong Khóa 1


<a name="toc_40015_1.2"></a>
## 1.2 Tài liệu tham khảo hữu ích
- Tài liệu NumPy bao gồm phần giới thiệu cơ bản: [NumPy.org](https://NumPy.org/doc/stable/)
- Chủ đề feature đầy thử thách: [NumPy Broadcasting](https://NumPy.org/doc/stable/user/basics.broadcasting.html)


<a name="toc_40015_2"></a>
#2 Python và NumPy <a name='Python and NumPy'></a>
Python là ngôn ngữ lập trình mà chúng ta sẽ sử dụng trong khóa học này. Nó có một tập hợp các kiểu dữ liệu số và các phép toán số học. NumPy là thư viện mở rộng các khả năng cơ bản của python để thêm tập dữ liệu phong phú hơn bao gồm nhiều loại số hơn, vectors, matrices và nhiều hàm matrix. NumPy và python phối hợp với nhau khá liền mạch. Toán tử số học Python hoạt động trên các kiểu dữ liệu NumPy và nhiều hàm NumPy sẽ chấp nhận các kiểu dữ liệu python.


<a name="toc_40015_3"></a>
#3 Vectors
<a name="toc_40015_3.1"></a>
## 3.1 Tóm tắt
<img align="right" src="./images/C1_W2_Lab04_Vectors.PNG" style="width:340px;" >Vectors, như bạn sẽ sử dụng chúng trong khóa học này, được sắp xếp theo thứ tự các số arrays. Trong ký hiệu, vectors được biểu thị bằng chữ in đậm chữ thường như $\mathbf{x}$.  Các phần tử của vector đều có cùng loại. Ví dụ: vector không chứa cả ký tự và số. Số phần tử trong array thường được gọi là *thứ nguyên* mặc dù các nhà toán học có thể thích *thứ hạng* hơn. vector được hiển thị có kích thước $n$. Các phần tử của vector có thể được tham chiếu bằng một chỉ mục. Trong cài đặt toán học, các chỉ mục thường chạy từ 1 đến n. Trong khoa học máy tính và các lab này, việc lập chỉ mục thường chạy từ 0 đến n-1.  Trong ký hiệu, các phần tử của vector, khi được tham chiếu riêng lẻ sẽ chỉ ra chỉ mục trong chỉ số dưới, ví dụ: phần tử $0^{th}$, của vector $\mathbf{x}$ là $x_0$. Lưu ý, x không được in đậm trong trường hợp này.


<a name="toc_40015_3.2"></a>
## 3.2 NumPy Arrays

Cấu trúc dữ liệu cơ bản của NumPy là một *array* có n chiều, có thể lập chỉ mục, chứa các phần tử cùng loại (`dtype`). Ngay lập tức, bạn có thể nhận thấy chúng ta đã quá tải thuật ngữ 'thứ nguyên'. Ở trên là số phần tử trong vector, ở đây, thứ nguyên đề cập đến số lượng chỉ mục của array. array một chiều hoặc 1-D có một chỉ mục. Trong Khóa 1, chúng ta sẽ biểu thị vectors là NumPy 1-D arrays. 

 - 1-D array, shape(n,): n phần tử được đánh chỉ mục từ [0] đến [n-1]


<a name="toc_40015_3.3"></a>
## 3.3 Tạo Vector


Các quy trình tạo dữ liệu trong NumPy thường sẽ có parameter đầu tiên là shape của đối tượng. Đây có thể là một giá trị duy nhất cho kết quả 1-D hoặc một bộ (n,m,...) chỉ định shape của kết quả. Dưới đây là ví dụ về cách tạo vectors bằng cách sử dụng các quy trình này.


In [2]:
# Các quy trình NumPy phân bổ bộ nhớ và điền giá trị vào arraysa = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.16054681 0.65264985 0.98302218 0.29864795], a shape = (4,), a data type = float64


Một số quy trình tạo dữ liệu không cần bộ shape:


In [3]:
# Các quy trình NumPy phân bổ bộ nhớ và điền giá trị vào arrays nhưng không chấp nhận shape làm đối số inputa = np.arange(4.);              print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.04467047 0.14854614 0.24949402 0.02417095], a shape = (4,), a data type = float64


Các giá trị cũng có thể được chỉ định theo cách thủ công.


In [4]:
# Các quy trình NumPy phân bổ bộ nhớ và điền các giá trị do người dùng chỉ địnha = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


Tất cả những điều này đã tạo ra một vector `a` một chiều với bốn phần tử. `a.shape` trả về kích thước. Ở đây chúng ta thấy a.shape = `(4,)` biểu thị array 1-d với 4 phần tử.


<a name="toc_40015_3.4"></a>
## 3.4 Thao tác trên Vectors
Hãy cùng khám phá một số thao tác sử dụng vectors.
<a name="toc_40015_3.4.1"></a>
### 3.4.1 Lập chỉ mục
Các phần tử của vectors có thể được truy cập thông qua lập chỉ mục và cắt. NumPy cung cấp một bộ khả năng lập chỉ mục và cắt lát rất đầy đủ. Chúng ta sẽ chỉ khám phá những điều cơ bản cần thiết cho khóa học ở đây. Tham khảo [Slicing and Indexing](https://NumPy.org/doc/stable/reference/arrays.indexing.html) để biết thêm chi tiết.  
**Lập chỉ mục** có nghĩa là đề cập đến *một phần tử* của array theo vị trí của nó trong array.  
**Cắt** có nghĩa là lấy một *tập hợp con* các phần tử từ array dựa trên chỉ mục của chúng.  
NumPy bắt đầu lập chỉ mục ở mức 0 nên phần tử thứ 3 của vector $\mathbf{a}$ là `a[2]`.


In [5]:
# Hoạt động lập chỉ mục vector trên vectors 1-Da = np.arange(10)
print(a)

# truy cập một phần tửprint(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")

# truy cập phần tử cuối cùng, chỉ số âm được tính từ cuốiprint(f"a[-1] = {a[-1]}")

# các chỉ mục phải nằm trong phạm vi của vector nếu không chúng sẽ tạo ra lỗitry:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


<a name="toc_40015_3.4.2"></a>
### 3.4.2 Cắt lát
Việc cắt lát tạo ra một array gồm các chỉ mục bằng cách sử dụng một bộ ba giá trị (`start:stop:step`). Một tập hợp con các giá trị cũng hợp lệ. Việc sử dụng nó được giải thích rõ nhất bằng ví dụ:


In [6]:
# Hoạt động cắt lát vectora = np.arange(10)
print(f"a         = {a}")

# truy cập 5 phần tử liên tiếp (bắt đầu: dừng: bước)c = a[2:7:1];     print("a[2:7:1] = ", c)

# truy cập 3 phần tử cách nhau bằng haic = a[2:7:2];     print("a[2:7:2] = ", c)

# truy cập tất cả các phần tử chỉ số 3 trở lênc = a[3:];        print("a[3:]    = ", c)

# truy cập tất cả các phần tử bên dưới chỉ mục 3c = a[:3];        print("a[:3]    = ", c)

# truy cập tất cả các yếu tốc = a[:];         print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


<a name="toc_40015_3.4.3"></a>
### 3.4.3 Hoạt động vector đơn lẻ
Có một số thao tác hữu ích liên quan đến các thao tác trên một vector.


In [7]:
a = np.array([1,2,3,4])
print(f"a             : {a}")
# các phần tử phủ định của ab = -a 
print(f"b = -a        : {b}")

# tổng tất cả các phần tử của a, trả về scalarb = np.sum(a) 
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


<a name="toc_40015_3.4.4"></a>
### 3.4.4 Vector Vector hoạt động theo từng phần tử
Hầu hết các phép toán số học, logic và so sánh của NumPy cũng áp dụng cho vectors. Các toán tử này hoạt động trên cơ sở từng phần tử. Ví dụ 
$$ \mathbf{a} + \mathbf{b} = \sum_{i=0}^{n-1} a_i + b_i $$


In [8]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


Tất nhiên, để điều này hoạt động chính xác, vectors phải có cùng kích thước:


In [9]:
# thử thao tác vector không khớpc = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


<a name="toc_40015_3.4.5"></a>
### 3.4.5 Hoạt động Scalar Vector
Vectors có thể được 'thu nhỏ' theo các giá trị scalar. Giá trị scalar chỉ là một con số. scalar nhân tất cả các phần tử của vector.


In [10]:
a = np.array([1, 2, 3, 4])

# nhân a với scalarb = 5 * a 
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


<a name="toc_40015_3.4.6"></a>
### 3.4.6 Vector Vector dot product
dot product là trụ cột của Đại số tuyến tính và NumPy. Đây là một thao tác được sử dụng rộng rãi trong khóa học này và cần được hiểu rõ. dot product được hiển thị bên dưới.


<img src="./images/C1_W2_Lab04_dot_notrans.gif" width=800>


Dot product nhân các giá trị trong hai phần tử vectors rồi tính tổng kết quả.
Vector dot product yêu cầu kích thước của hai vectors phải giống nhau.


Hãy triển khai phiên bản dot product của riêng chúng ta bên dưới:

**Sử dụng vòng lặp for**, triển khai hàm trả về dot product của hai vectors. Hàm trả về các đầu vào đã cho $a$ và $b$:
$$ x = \sum_{i=0}^{n-1} a_i b_i $$
Giả sử cả `a` và `b` đều là shape giống nhau.


In [11]:
def my_dot(a, b): 
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [12]:
# kiểm tra 1-Da = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


Lưu ý, dot product dự kiến ​​sẽ trả về giá trị scalar. 

Hãy thử các thao tác tương tự bằng `np.dot`.


In [13]:
# kiểm tra 1-Da = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")


NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


Ở trên, bạn sẽ lưu ý rằng kết quả của 1-D phù hợp với việc triển khai của chúng ta.


<a name="toc_40015_3.4.7"></a>
### 3.4.7 Nhu cầu về tốc độ: vector so với vòng lặp for
Chúng ta sử dụng thư viện NumPy vì nó cải thiện hiệu suất bộ nhớ tốc độ. Hãy chứng minh:


In [14]:
np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 29.9268 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 2137.4848 ms 


Vì vậy, vectorization cung cấp tốc độ tăng tốc lớn trong ví dụ này. Điều này là do NumPy tận dụng tốt hơn khả năng song song dữ liệu có sẵn trong phần cứng cơ bản. GPU và CPU hiện đại triển khai các đường ống Hướng dẫn đơn, Nhiều dữ liệu (SIMD) cho phép thực hiện song song nhiều hoạt động. Điều này rất quan trọng trong Machine Learning nơi tập dữ liệu thường rất lớn.


<a name="toc_12345_3.4.8"></a>
### 3.4.8 Các thao tác Vector Vector trong Khóa 1
Các thao tác Vector Vector sẽ xuất hiện thường xuyên trong khóa học 1. Đây là lý do:
- Trong tương lai, các ví dụ của chúng ta sẽ được lưu trữ trong array, `X_train` có kích thước (m,n). Điều này sẽ được giải thích thêm theo ngữ cảnh, nhưng điều quan trọng cần lưu ý ở đây là array hoặc matrix 2 chiều (xem phần tiếp theo về matrices).
- `w` sẽ là vector 1 chiều của shape (n,).
- chúng ta sẽ thực hiện các thao tác bằng cách lặp qua các ví dụ, trích xuất từng ví dụ để làm việc riêng lẻ bằng cách lập chỉ mục X. Ví dụ:`X[i]`
- `X[i]` trả về giá trị shape(n,), vector 1 chiều. Do đó, các hoạt động liên quan đến `X[i]` thường là vector-vector.  

Đó là một lời giải thích hơi dài dòng, nhưng việc căn chỉnh và hiểu hình dạng của các toán hạng là điều quan trọng khi thực hiện các phép toán vector.


In [15]:
# hiển thị ví dụ khóa học 1 chungX = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,)
w has shape (1,)
c has shape ()


<a name="toc_40015_4"></a>
#4 Matrices


<a name="toc_40015_4.1"></a>
## 4.1 Tóm tắt
Matrices, là arrays hai chiều. Các phần tử của matrix đều cùng loại. Trong ký hiệu, matrices được ký hiệu bằng chữ hoa, chữ đậm như $\mathbf{X}$. Trong lab này và các lab khác, `m` thường là số hàng và `n` thường là số cột. Các phần tử của matrix có thể được tham chiếu bằng chỉ mục hai chiều. Trong cài đặt toán học, các số trong chỉ mục thường chạy từ 1 đến n. Trong khoa học máy tính và các lab này, việc lập chỉ mục sẽ chạy từ 0 đến n-1.  
<figure>
    <center> <img src="./images/C1_W2_Lab04_Matrices.PNG"  alt='missing'  width=900><center/>
    <figcaption> Ký hiệu Matrix chung, chỉ mục thứ 1 là hàng, thứ 2 là cột </figcaption>
<figure/>


<a name="toc_40015_4.2"></a>
## 4.2 NumPy Arrays

Cấu trúc dữ liệu cơ bản của NumPy là một *array* có n chiều, có thể lập chỉ mục, chứa các phần tử cùng loại (`dtype`). Những điều này đã được mô tả trước đó. Matrices có chỉ số hai chiều (2-D) [m,n].

Trong Khóa 1, matrices 2-D được sử dụng để lưu giữ dữ liệu training. Dữ liệu Training là các ví dụ $m$ do $n$ features tạo ra (m,n) array. Khóa 1 không thực hiện các thao tác trực tiếp trên matrices mà thường trích xuất một ví dụ dưới dạng vector và thực hiện trên đó. Dưới đây bạn sẽ xem xét: 
- tạo dữ liệu
- cắt và lập chỉ mục


<a name="toc_40015_4.3"></a>
## 4.3 Tạo Matrix
Các chức năng tương tự đã tạo vectors 1-D sẽ tạo arrays 2-D hoặc n-D. Dưới đây là một số ví dụ


Dưới đây, bộ dữ liệu shape được cung cấp để đạt được kết quả 2-D. Lưu ý cách NumPy sử dụng dấu ngoặc để biểu thị từng thứ nguyên. Lưu ý thêm NumPy, khi in, sẽ in một hàng trên mỗi dòng.


In [16]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.44236513]]


Người ta cũng có thể chỉ định dữ liệu theo cách thủ công. Kích thước được chỉ định bằng các dấu ngoặc bổ sung phù hợp với định dạng in ở trên.


In [17]:
# Các quy trình NumPy phân bổ bộ nhớ và điền các giá trị do người dùng chỉ địnha = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


<a name="toc_40015_4.4"></a>
## 4.4 Thao tác trên Matrices
Hãy cùng khám phá một số thao tác sử dụng matrices.


<a name="toc_40015_4.4.1"></a>
### 4.4.1 Lập chỉ mục


Matrices bao gồm chỉ mục thứ hai. Hai chỉ mục mô tả [hàng, cột]. Access có thể trả về một phần tử hoặc một hàng/cột. Xem bên dưới:


In [18]:
# Hoạt động lập chỉ mục vector trên matricesa = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

# truy cập một phần tửprint(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

# truy cập một hàngprint(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int64'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


Điều đáng chú ý là ví dụ cuối cùng. Truy cập matrix chỉ bằng cách chỉ định hàng sẽ trả về *1-D vector*.


**Định hình lại**  
Ví dụ trước sử dụng [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) đến shape array.  
`a = np.arange(6).reshape(-1, 2) `   
Dòng code này lần đầu tiên tạo ra *1-D Vector* gồm sáu phần tử. Sau đó, nó định hình lại vector đó thành *2-D* array bằng lệnh định hình lại. Điều này có thể đã được viết:  
`a = np.arange(6).reshape(3, 2) `  
Để đến cùng 3 hàng, 2 cột array.
Đối số -1 yêu cầu quy trình tính toán số hàng dựa trên kích thước của array và số cột.


<a name="toc_40015_4.4.2"></a>
### 4.4.2 Cắt lát
Việc cắt lát tạo ra một array gồm các chỉ mục bằng cách sử dụng một bộ ba giá trị (`start:stop:step`). Một tập hợp con các giá trị cũng hợp lệ. Việc sử dụng nó được giải thích rõ nhất bằng ví dụ:


In [19]:
# vector Hoạt động cắt 2-Da = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

# truy cập 5 phần tử liên tiếp (bắt đầu: dừng: bước)print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

# truy cập 5 phần tử liên tiếp (bắt đầu: dừng: bước) thành hai hàngprint("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# truy cập tất cả các yếu tốprint("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# truy cập tất cả các phần tử trong một hàng (cách sử dụng rất phổ biến)print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# giống nhưprint("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array


<a name="toc_40015_5.0"></a>
## Congratulations!
Trong lab này, bạn đã thành thạo features của Python và NumPy cần thiết cho Khóa 1.
